/* External datasets and run selection drive these synchronization effects. */
/* oxlint-disable react/set-state-in-effect */
import { useEffect, useState } from 'react'
import { MapContainer, ImageOverlay, GeoJSON, CircleMarker, Popup } from 'react-leaflet'
import { apiBase, request, artifactUrl } from '../api'
import './environment.css'

const transitions = [['#2b5faa','1 Permanent'],['#38a752','2 New permanent'],['#c14436','3 Lost permanent'],['#6fafd6','4 Seasonal'],['#8cc354','5 New seasonal'],['#df9352','6 Lost seasonal'],['#5d69ad','7 Seasonal → permanent'],['#7d60aa','8 Permanent → seasonal'],['#967878','9 Ephemeral permanent'],['#c3a5a0','10 Ephemeral seasonal']]
const number = (n,d=2) => n == null ? '—' : Number(n).toFixed(d)

function RainChart({ data }) {
  const max=Math.max(1,...data.map(m=>m.total_mm || 0)); const width=720, height=210, bar=640/data.length
  return <svg viewBox={`0 0 ${width} ${height+55}`} role="img" aria-label="Monthly rainfall totals in millimetres" className="rain-chart"><text x="4" y="14" fontSize="11">mm</text>{[0,.5,1].map(t=><g key={t}><line x1="45" x2="705" y1={height-t*(height-30)} y2={height-t*(height-30)} stroke="#dbe2d7"/><text x="4" y={height-t*(height-30)+4} fontSize="10">{Math.round(t*max)}</text></g>)}{data.map((m,i)=><g key={m.month}><rect x={50+i*bar} y={height-(m.total_mm || 0)/max*(height-30)} width={bar*.72} height={Math.max(1,(m.total_mm || 0)/max*(height-30))} fill={m.total_mm == null ? '#bb9965' : '#3c8072'}><title>{m.month}: {m.total_mm == null ? 'Incomplete month' : `${m.total_mm} mm`} · {m.valid_days}/{m.expected_days} days</title></rect>{i%2===0 && <text x={50+i*bar} y={height+17} transform={`rotate(35 ${50+i*bar} ${height+17})`} fontSize="9">{m.month}</text>}</g>)}</svg>
}

function EvidenceMap({ boundary, selected, historical, field }) {
  return <MapContainer bounds={selected?.bounds || [[10.14,78.77],[11.19,79.58]]} className="environment-map" scrollWheelZoom={false} preferCanvas>
    {boundary && <GeoJSON data={boundary} style={{color:'#3b5748',weight:1,fillOpacity:0.08}}/>}
    {selected && <ImageOverlay key={selected.image_url} url={apiBase+selected.image_url} bounds={selected.bounds} opacity={.9}/>}
    {historical?.features?.length>0 && <GeoJSON key={JSON.stringify(historical)} data={historical} style={{color:'#9b493a',weight:3,fillOpacity:.15}} onEachFeature={(f,l)=>{const el=document.createElement('div');el.textContent=`${f.properties.title} · ${f.properties.period} · ${f.properties.confidence} · ${f.properties.interpretation} · Source: ${f.properties.source}`;l.bindPopup(el)}}/>}
    {field?.map(r=><CircleMarker key={r.id} center={[r.latitude,r.longitude]} radius={4} pathOptions={{color:'#713b71'}}><Popup>{r.id} · {r.target}: {r.value}<br/>{r.source}</Popup></CircleMarker>)}
  </MapContainer>
}

export default function EnvironmentEvidence({ boundary, run, onRefresh }) {
  const [data,setData]=useState(null), [error,setError]=useState(''), [busy,setBusy]=useState(false)
  const [point,setPoint]=useState(0), [layerId,setLayerId]=useState('ndvi'), [layer,setLayer]=useState(null)
  const [season,setSeason]=useState('latest'), [history,setHistory]=useState(null)
  const [comparison,setComparison]=useState(null), [target,setTarget]=useState('surface_water_presence'), [source,setSource]=useState('satellite')
  const [importMessage,setImportMessage]=useState(''), [comparisonError,setComparisonError]=useState('')
  const [reload,setReload]=useState(0)
  const runId=run?.status==='completed'?run.id:null
  useEffect(()=>{
    let stopped=false,timer
    async function load(){try{const d=await request('/environment');if(stopped)return;setData(d);setError('');if(['queued','running'].includes(d.job?.status))timer=setTimeout(load,1800)}catch(e){if(!stopped)setError(e.message)}}
    load(); request('/environment/historical-features').then(d=>{if(!stopped)setHistory(d)}).catch(e=>{if(!stopped)setError(e.message)})
    return()=>{stopped=true;clearTimeout(timer)}
  },[reload])
  useEffect(()=>{
    let stop=false;setLayer(null)
    if(data?.datasets.some(d=>d.layers.some(l=>l.id===layerId))) request(`/environment/layer/${layerId}`).then(d=>{
      if(stop)return
      if(season!=='latest' && ['ndvi','ndwi'].includes(layerId)){const [year,quarter]=season.split('-');d.image_url=`/api/environment/season/${year}/${quarter}/${layerId}`;d.title=`${layerId.toUpperCase()} · ${year} Q${quarter}`}
      setLayer(d)
    }).catch(e=>{if(!stop)setError(e.message)})
    return()=>{stop=true}
  },[data,layerId,season])
  useEffect(()=>{
    let stop=false;setComparison(null);setComparisonError('')
    if(runId)request(`/environment/validation/${runId}?target=${target}&source=${source}`).then(d=>{if(!stop)setComparison(d)}).catch(e=>{if(!stop)setComparisonError(e.message)})
    return()=>{stop=true}
  },[runId,target,source])
  async function acquire(){setBusy(true);setError('');try{await request('/environment/acquire',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})});setReload(n=>n+1);onRefresh?.()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function upload(event,kind){const file=event.target.files[0];event.target.value='';if(!file)return;setBusy(true);setError('');setImportMessage('');try{if(file.size>5*1024*1024)throw new Error('JSON must be smaller than 5 MiB');const body=JSON.stringify(JSON.parse(await file.text()));const d=await request(`/environment/${kind}`,{method:'PUT',headers:{'Content-Type':'application/json'},body});setImportMessage(`${d.imported} records imported. ${d.note}`);setReload(n=>n+1);onRefresh?.()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const rain=data?.rainfall?.series[point], satellite=data?.datasets.find(d=>d.id==='satellite'), active=['queued','running'].includes(data?.job?.status)
  return <div className="environment-page"><div className="notice"><p><strong>Current acquired evidence.</strong> Analysis runs retain their original source snapshots. Create a new analysis after acquisition or import to use the new map layers and reference comparisons. These sources contextualise the terrain score; they do not establish storage capacity.</p></div>{error&&<div className="error" role="alert">{error}</div>}<div className="environment-actions"><button className="primary" onClick={acquire} disabled={busy||active}>{active?'Acquiring evidence…':'Acquire / refresh public data'}</button><button className="text-button" onClick={()=>{setReload(n=>n+1);onRefresh?.()}}>Reload catalogue</button><span>Default: rainfall 2024–2025 · Sentinel 2025 · JRC 1984–2024</span></div>{active&&<div className="progress-banner" role="status">{data.job.stage}<span>{data.job.progress}%</span></div>}{data?.job?.errors&&Object.entries(data.job.errors).map(([k,v])=><div className="error" role="alert" key={k}>{k}: {v}</div>)}<div className="environment-cards">{data?.datasets.map(d=><section className="panel" key={d.id}><span className="eyebrow">{d.timescale}</span><h3>{d.title}</h3><span className="badge">{d.status}</span><p>{d.note}</p><small>{d.observed_at} · acquired {d.retrieved_at?.slice(0,10)}</small></section>)}</div>
    <section className="panel environmental-rain"><div className="panel-header"><h2>Dated rainfall</h2>{rain&&<label>Rainfall grid cell<select aria-label="Rainfall grid cell" value={point} onChange={e=>setPoint(Number(e.target.value))}>{data.rainfall.series.map((s,i)=><option key={s.id} value={i}>{s.latitude}° N, {s.longitude}° E</option>)}</select></label>}</div>{rain?<><p>{data.rainfall.note}</p><RainChart data={rain.months}/><details><summary>Monthly totals and completeness</summary><div className="table-scroll"><table><thead><tr><th>MONTH</th><th>TOTAL mm</th><th>VALID DAYS</th></tr></thead><tbody>{rain.months.map(m=><tr key={m.month}><td>{m.month}</td><td>{number(m.total_mm)}</td><td>{m.valid_days}/{m.expected_days}</td></tr>)}</tbody></table></div></details></>:<p>No rainfall series acquired yet.</p>}</section>
    <section className="panel environmental-layers"><div className="panel-header"><h2>Environmental layers</h2><label>Evidence layer<select aria-label="Evidence layer" value={layerId} onChange={e=>setLayerId(e.target.value)}>{data?.datasets.flatMap(d=>d.layers).map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select></label></div>{['ndvi','ndwi'].includes(layerId)&&<label className="season-select">Observation window<select aria-label="Observation window" value={season} onChange={e=>setSeason(e.target.value)}><option value="latest">Latest acquired quarter</option>{satellite?.seasons?.map(s=><option key={s.label} value={`${s.start.slice(0,4)}-${Math.ceil(Number(s.start.slice(5,7))/3)}`}>{s.label} · {s.coverage_percent}% clear coverage</option>)}</select></label>}<EvidenceMap boundary={boundary} selected={layer} historical={history} field={data?.field_records}/>{layer&&<div className="environment-legend"><strong>{layer.title}</strong>{layerId==='transitions'?<div className="transition-legend">{transitions.map(([color,title])=><span key={title}><i style={{background:color}}/>{title}</span>)}</div>:<><span>{layer.range[0]} <i className="legend-gradient"/> {layer.range[1]} {layer.units}</span><small>Transparent cells have no data. {(season==='latest'||!['ndvi','ndwi'].includes(layerId))?`${layer.coverage_percent}% usable coverage.`:'Coverage is reported by observation window.'}</small></>}<p>{layer.note}</p>{['occurrence','transitions'].includes(layerId)&&<small>Source: EC JRC/Google · v1.5 · 1984–2024</small>}</div>}</section>
    {satellite&&<section className="panel"><h2>Seasonal vegetation & water observations</h2><p>Values describe the clear cells acquired in each mosaic. Different coverage and tile dates can affect comparisons; these are representative observations, not quarterly means.</p><div className="table-scroll"><table><thead><tr><th>WINDOW</th><th>NDVI MEAN</th><th>NDWI MEAN</th><th>CLEAR COVERAGE</th><th>ACTUAL ACQUISITIONS</th></tr></thead><tbody>{satellite.seasons.map(s=><tr key={s.label}><td>{s.label}</td><td>{number(s.ndvi_mean,3)}</td><td>{number(s.ndwi_mean,3)}</td><td>{s.coverage_percent}%</td><td>{s.scenes.filter(s=>s.datetime).map(s=>s.datetime.slice(0,10)).join(', ')}</td></tr>)}</tbody></table></div></section>}
    <section className="panel validation-panel"><h2>Independent reference comparison</h2><p>Compare the selected run's terrain-only score with observations that were not used to fit it. Satellite reference results apply only to surface-water association.</p><div className="validation-controls"><label>Reference source<select aria-label="Reference source" value={source} onChange={e=>{setSource(e.target.value);if(e.target.value==='satellite')setTarget('surface_water_presence')}}><option value="satellite">JRC / Landsat reference</option><option value="field">Imported field outcomes</option></select></label><label>Observed outcome<select aria-label="Observed outcome" value={target} disabled={source==='satellite'} onChange={e=>setTarget(e.target.value)}><option value="surface_water_presence">Surface water presence</option><option value="water_storage_suitability">Water-storage suitability</option><option value="archaeological_presence">Archaeological presence</option></select></label></div>{comparisonError&&<p role="alert">{comparisonError}</p>}{!runId?<p>Select a completed analysis run first.</p>:comparison?<><span className="badge amber">{comparison.status}</span><div className="comparison-metrics">{[['Samples',comparison.samples],['Balanced accuracy',comparison.balanced_accuracy],['Precision',comparison.precision],['Recall',comparison.recall],['ROC AUC',comparison.auc]].map(([label,v])=><div key={label}><small>{label}</small><strong>{number(v,label==='Samples'?0:3)}</strong></div>)}</div><p>{comparison.note}</p>{comparison.requirement&&<p>{comparison.requirement}</p>}{comparison.confusion&&<p>True positive {comparison.confusion.tp} · true negative {comparison.confusion.tn} · false positive {comparison.confusion.fp} · false negative {comparison.confusion.fn}. Fixed high-terrain threshold: {comparison.threshold}.</p>}<small>Run {runId.slice(0,8)} · validation uses that run's frozen evidence.</small><details className="reference-map"><summary>Inspect reference sample locations</summary><EvidenceMap boundary={boundary} field={comparison.points?.map((p,i)=>({...p,id:`reference-${i+1}`,target:comparison.target,value:p.observed,source:comparison.source}))}/></details></>:<p>Loading comparison…</p>}<details><summary>Import independent field records</summary><p>Upload the documented JSON array with coordinates, observation date, target, value, source, method and independence statement. Binary outcomes use 0/1; measured infiltration uses mm/h and is recorded as field context. Existing IDs are updated; other records are retained.</p><input aria-label="Field validation JSON" type="file" accept=".json" disabled={busy} onChange={event=>upload(event,'field-records')}/><p>{data?.field_records?.length||0} field records currently stored. Create a new run after importing.</p></details></section>
    <section className="panel"><h2>Palaeochannels & older map evidence</h2><p>Red/orange historical-transition pixels identify lost satellite-era water. They are investigation leads, not confirmed palaeochannels. Import sourced WGS84 GeoJSON interpretations from georeferenced maps, sediment surveys, or field work to overlay them above.</p><details><summary>Import historical map features</summary><p>Each feature requires title, source, period, interpretation and confidence (documented, candidate, or field verified). The app preserves the contributor's interpretation separately from the satellite reference.</p><input aria-label="Historical GeoJSON" type="file" accept=".json,.geojson" disabled={busy} onChange={event=>upload(event,'historical-features')}/></details><p>{data?.history_features||0} historical features imported.</p></section>{importMessage&&<div className="notice" role="status">{importMessage}</div>}
    {runId&&run?.summary?.environment&&<section className="panel"><h2>Reproducible evidence exports</h2><div className="export-links"><a href={artifactUrl(runId,'environment.json')} download>Source snapshot JSON</a>{run.summary.surface_water_comparison?.method_version&&<a href={artifactUrl(runId,'comparisons.json')} download>Reference comparison JSON</a>}{run.summary.environment.rainfall_sha256&&<a href={artifactUrl(runId,'rainfall.json')} download>Rainfall series JSON</a>}{[...run.summary.environment.layers,...(run.summary.environment.seasonal_layers||[])].map(l=><a key={l.raster} href={artifactUrl(runId,l.raster)} download>{l.title} GeoTIFF</a>)}</div></section>}
  </div>
}
