const { createRequire } = require('node:module');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const requireFrontend = createRequire(path.resolve(__dirname, '../frontend/package.json'));
const { chromium } = requireFrontend('playwright');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const output = path.resolve(__dirname, '../artifacts');
  fs.mkdirSync(output, { recursive: true });
  const document = {asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{mesh:0}],meshes:[{primitives:[{attributes:{POSITION:0}}]}],buffers:[{byteLength:36}],bufferViews:[{buffer:0,byteOffset:0,byteLength:36}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[0,0,0],max:[1,1,0]}]};
  const json = Buffer.from(JSON.stringify(document));
  const meta = Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);
  const binary = Buffer.alloc(36); [0,0,0,1,0,0,0,1,0].forEach((v,i)=>binary.writeFloatLE(v,i*4));
  const header = Buffer.alloc(20); header.write('glTF'); header.writeUInt32LE(2,4); header.writeUInt32LE(28+meta.length+binary.length,8); header.writeUInt32LE(meta.length,12); header.writeUInt32LE(0x4E4F534A,16);
  const binHeader=Buffer.alloc(8); binHeader.writeUInt32LE(binary.length,0); binHeader.writeUInt32LE(0x004E4942,4);
  fs.writeFileSync(path.join(output,'test-triangle.glb'),Buffer.concat([header,meta,binHeader,binary]));
  const original = await (await page.request.get('http://127.0.0.1:8000/api/heritage/relation-6668806')).json();
  const originalModel = original.asset.tier === 3 ? await (await page.request.get('http://127.0.0.1:8000'+original.asset.url)).body() : null;
  try {
    await page.goto('http://127.0.0.1:8000', { waitUntil: 'networkidle' });
    await page.getByLabel('Find a heritage site').fill('show me Brihadeeswarar Temple in 3D');
    await page.getByRole('button', {name:'Explore site',exact:true}).click();
    await page.getByRole('heading', {name:'Brihadishwara Temple',exact:true}).waitFor();
    await page.getByRole('button', {name:'Reset camera',exact:true}).waitFor();
    await page.waitForFunction(() => ![...document.querySelectorAll('button')].find(b => b.textContent === 'Reset camera')?.disabled);
    assert(await page.locator('canvas').count() === 1, '3D renderer missing');
    await page.getByText('Use your own model',{exact:true}).click();
    await page.getByLabel('Upload GLB').setInputFiles({name:'invalid.glb',mimeType:'model/gltf-binary',buffer:Buffer.from('invalid')});
    await page.getByRole('alert').filter({hasText:'GLB'}).waitFor();
    await page.getByLabel('Upload GLB').setInputFiles(path.join(output,'test-triangle.glb'));
    await page.getByText('User-supplied model · unverified',{exact:true}).waitFor();
    await page.waitForFunction(() => ![...document.querySelectorAll('button')].find(b => b.textContent === 'Reset camera')?.disabled);
    await page.getByRole('button',{name:'Use reconstructed approximation',exact:true}).click();
    await page.getByText('Reconstructed approximation',{exact:true}).waitFor();
    await page.getByText('0–5 cm', {exact:false}).first().waitFor();
    await page.waitForFunction(() => document.querySelector('.experiment-score strong')?.textContent !== undefined);
    const before = await page.locator('.experiment-score strong').textContent();
    assert.notEqual(before, 'Unassessed', 'Expected live terrain sample');
    await page.getByRole('checkbox', {name:/Slope \/ flatness/}).uncheck();
    const after = await page.locator('.experiment-score strong').textContent();
    assert.notEqual(before, after, 'Disabling slope must change the live score');
    await page.getByRole('checkbox', {name:/Relative lower position/}).uncheck();
    assert.equal(await page.locator('.experiment-score strong').textContent(), 'Unassessed');
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:path.join(output,'heritage-desktop.png'),fullPage:true});
    await page.getByRole('button', {name:'Learning library',exact:true}).click();
    await page.getByLabel('Search the library').fill('Manora');
    await page.getByRole('button', {name:/fort Manora Fort/}).click();
    await page.getByRole('heading', {name:'Manora Fort',exact:true}).waitFor();
    await page.getByText('unavailable · depth below ground').waitFor();
    await page.getByRole('button', {name:'Glossary',exact:true}).click();
    await page.getByLabel('Search the library').fill('NDVI');
    await page.locator('.library-card').first().click();
    await page.locator('.library-reader').getByRole('heading',{name:/NDVI/}).waitFor();
    await page.getByRole('button', {name:'Learning modules',exact:true}).click();
    await page.locator('.library-card').filter({hasText:'Reading a soil profile'}).click();
    await page.getByLabel('Live project example').waitFor();
    await page.locator('.library-reader .soil-view').waitFor();
    await page.getByLabel('Workspace mode').selectOption('student');
    await page.reload({waitUntil:'networkidle'});
    await page.getByRole('heading', {name:'Learning library',exact:true}).waitFor();
    await page.screenshot({path:path.join(output,'library-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(output,'library-mobile.png'),fullPage:true});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),'Mobile library overflow');
    await page.getByLabel('Search the library').fill('Brihadishwara');
    await page.locator('.library-card').first().click();
    await page.getByRole('heading',{name:'Brihadishwara Temple',exact:true}).waitFor();
    await page.screenshot({path:path.join(output,'heritage-mobile.png'),fullPage:true});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),'Mobile viewer overflow');
    await page.setViewportSize({width:1440,height:1080});
    await page.getByRole('button',{name:'Settlement context',exact:true}).click();
    await page.getByRole('button',{name:'Locate Brihadishwara Temple',exact:true}).click();
    await page.waitForTimeout(1800); // Leaflet flyTo animation
    const map = await page.locator('.leaflet-container').boundingBox();
    await page.mouse.click(map.x+map.width/2,map.y+map.height/2);
    await page.getByRole('button',{name:'Open 3D & soil profile',exact:true}).click();
    await page.getByRole('heading',{name:'Site 3D & subsurface',exact:true}).waitFor();
    assert.deepEqual(errors,[],'Browser runtime errors');
    console.log('Heritage browser checks passed: lookup, WebGL, soil, live factors, search, glossary, lessons, mode persistence and mobile.');
  } finally {
    if(originalModel) await page.request.put('http://127.0.0.1:8000/api/heritage/relation-6668806/model',{data:originalModel});
    else await page.request.delete('http://127.0.0.1:8000/api/heritage/relation-6668806/model');
    await browser.close();
  }
})().catch(e=>{ console.error(e); process.exitCode=1; });
